### ISSUE TITLE
Feature Request: Add link outs to concept identifiers shown in the UI

### ISSUE THREAD

**Issue by bill-baumgartner** [UCDenver-ccp/Translator-TM-Provider-UI#3]
If it's an easy add, it would be beneficial to be able to click on a concept identifier to navigate to an external web page that provides further information about the concept. In the example shown in the attached screenshot, the Drugbank identifiers could link to https://go.drugbank.com/drugs/DB00273, and Mondo identifiers could link to https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0002184

<img width="1302" alt="Screen Shot 2023-05-10 at 11 17 08 AM" src="https://github.com/UCDenver-ccp/Translator-TM-Provider-UI/assets/7217210/d2c117b1-18be-45a9-9976-f3cfac274809">

**Comment by edgargaticaCU** [comment]
This should be relatively easy to do since it's mainly just appending the curie to a base URL. However, I would need base URLs for the other namespaces, if available. 
The subject and object curies are currently in the following namespaces: CHEBI, DRUGBANK, HP, MONDO, PR, and (optionally) UniProtKB.

**Comment by bill-baumgartner** [comment]
For the ontologies, we can make use of the OBO PURLs, e.g.,
`CHEBI:4031`: http://purl.obolibrary.org/obo/CHEBI_4031
`HP:0004322`: http://purl.obolibrary.org/obo/HP_0004322
`MONDO:0002184`:  http://purl.obolibrary.org/obo/MONDO_0002184
`PR:000017284`: http://purl.obolibrary.org/obo/PR_000017284

For Drugbank, we can link to the Drugbank website, e.g. `DRUGBANK:DB00273`: https://go.drugbank.com/drugs/DB00273

For Uniprot, we can also link to their website: e.g. `UniprotKB:P15692`: https://www.uniprot.org/uniprotkb/P15692/entry

**Comment by edgargaticaCU** [comment]
This has been added and deployed. The link outs are currently in the "Assertion" section below the sentence. I can also add them to the highlighted terms in the sentence if this is preferred.

**Comment by bill-baumgartner** [comment]
Fantastic! Thanks!
